port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  enabled: true
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
  fallback:
    - 8.8.8.8
    - 8.8.4.4
    - tls://1.0.0.1:853
    - tls://dns.google:853

proxy-providers:
  All:
    type: http
    url: "https://api.v1.mk/sub?target=clash&url=https://chromegoclash.marco.us.kg/&list=true&udp=true"
    # 可以使用任意类型的链接替换上面文字，多个链接使用英文符号的竖杠|隔开一起写上即可；也可以将Clash订阅链接替换掉整个引号""内的链接
    interval: 3600
    path: ./all.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

proxies:
# shadowsocks
# 所支持的加密方式与 go-shadowsocks2 保持一致
# 支持加密方式：
#   aes-128-gcm aes-192-gcm aes-256-gcm
#   aes-128-cfb aes-192-cfb aes-256-cfb
#   aes-128-ctr aes-192-ctr aes-256-ctr
#   rc4-md5 chacha20-ietf xchacha20
#   chacha20-ietf-poly1305 xchacha20-ietf-poly1305

# Shadowsocks
# 第一种配置
#- name: "你的SS节点1"               # 软件显示的节点名字
#  type: ss                                  # 代理类型
#  server: 1.2.4.8                          # 服务器 IP
#  port: 443                                 #  端口号
#  cipher: chacha20-ietf-poly1305   # 加密方法
#  password: "password"                # SS 密码
#  # udp: true                                #默认不开启

# Shadowsocks + simple-obfs
# 第二种配置
#- name: "你的SS节点2"               # 软件显示的节点名字
#  type: ss                                  # 代理类型
#  server: 1.2.4.8                          # 服务器 IP
#  port: 443                                 #  端口号
#  cipher: chacha20-ietf-poly1305   # 加密方法
#  password: "password"                # SS 密码
#  plugin: obfs
#  plugin-opts:
#    mode: tls # or http               #  大部分选择 HTTP
#  #  host: bing.com                  #  伪装

# Shadowsocks + v2ray-plugin
# 第三种配置
# - name: "你的SS节点3"
#   type: ss
#   server: 1.2.4.8
#   port: 443
#   cipher: chacha20-ietf-poly1305
#   password: "password"
#   plugin: v2ray-plugin
#   plugin-opts:
#     mode: websocket # no QUIC now
#     # tls: true # wss
#     # skip-cert-verify: true
#     # host: bing.com
#     # path: "/"
#     # mux: true
#     # headers:
#     #   custom: value

# vmess
# 支持加密方式：auto / aes-128-gcm / chacha20-poly1305 / none
- name: SG-Oracle_Cloud
  port: 443
  server: sgp.114514660.xyz
  type: vmess
  network: ws
  tls: true
  udp: true
  version: 2
  servername: sgp.114514660.xyz
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      host: sgp.114514660.xyz
  cipher: auto
  uuid: eb9fce11-dc4e-448d-9d66-cae7be51e77c
  alterId: .nan


# socks5
# - name: "socks"
#   type: socks5
#   server: server
#   port: 443
#   username: username
#   password: password
#   tls: true
#   skip-cert-verify: true
#   udp: true

# http
# - name: "http"
#   type: http
#   server: server
#   port: 443
#   username: username
#   password: password
#   tls: true # https
#   skip-cert-verify: true

# snell
# - name: "snell"
#   type: snell
#   server: server
#   port: 44046
#   psk: yourpsk
#   obfs-opts:
  #   mode: http # 或 tls
  #   host: bing.com

# Trojan的配置
# - name: "trojan"
#   type: trojan
#   server: server
#   port: 443
#   password: password
#   #上面几行为必选参数
#   #下面几行为可选参数  根据你的配置情况来
#   # udp: true
#   # sni: example.com # aka server name
#   # alpn:
#   #   - h2
#   #   - http/1.1
#   # skip-cert-verify: true

proxy-groups:
  - name: 🚀 节点选择
    type: select
    use:
      - All
    proxies:
      - ♻️ 自动选择
      - 🔯 故障转移
      - 🔮 负载均衡
      - 🔗 链式代理
      - DIRECT

  - name: ♻️ 自动选择
    type: url-test
    use:
       - All
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    tolerance: 50
    
  - name: 🔯 故障转移
    type: fallback
    use:
       - All
    url: "http://www.gstatic.com/generate_204"
    interval: 180
    
  - name: 🔮 负载均衡
    type: load-balance
    use:
       - All
    url: "http://www.gstatic.com/generate_204"
    interval: 180

  - name: 🔗 链式代理
    type: relay
    proxies:
       - ♻️ 自动选择
       - SG-Oracle_Cloud         #你的自建节点name

  - name: 🍎 苹果服务
    type: select
    proxies:
      - 🚀 节点选择
      - ♻️ 自动选择
      - 🎯 全球直连

  - name: 🎯 全球直连
    type: select
    proxies:
      - DIRECT
      - 🚀 节点选择
      - ♻️ 自动选择

  - name: 🛑 全球拦截
    type: select
    proxies:
      - REJECT
      - 🚀 节点选择

  - name: 🐟 漏网之鱼
    type: select
    proxies:
      - 🚀 节点选择
      - ♻️ 自动选择
      - 🎯 全球直连

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

rules:
  - RULE-SET,applications,🎯 全球直连
  - DOMAIN,clash.razord.top,🎯 全球直连
  - DOMAIN,yacd.haishan.me,🎯 全球直连
  - RULE-SET,private,🎯 全球直连
  - RULE-SET,reject,🛑 全球拦截
  - RULE-SET,icloud,🍎 苹果服务
  - RULE-SET,apple,🍎 苹果服务
  - RULE-SET,proxy,🚀 节点选择
  - RULE-SET,direct,🎯 全球直连
  - RULE-SET,lancidr,🎯 全球直连
  - RULE-SET,cncidr,🎯 全球直连
  - RULE-SET,telegramcidr,🚀 节点选择
  - GEOIP,LAN,🎯 全球直连
  - GEOIP,CN,🎯 全球直连
  - MATCH,🐟 漏网之鱼
